BUILD_DIR=/mnt/c/Users/Joe/Desktop/tmp-target
CONFIGURE_DIR=/mnt/c/Users/Joe/Desktop
NATIVE_BUILD_DIR=/mnt/c/Users/Joe/Desktop/tmp-native
PROJECT_TOP_DIR=/mnt/c/Users/Joe/Desktop
.PHONY : first_target
first_target : everything

include $(PROJECT_TOP_DIR)/project.mk
include $(PROJECT_TOP_DIR)/magic.mk
